spring.application.name=comissaoapi
server.port=8080

spring.datasource.url=jdbc:h2:mem:comissao_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

app.jwt.secret=troque-esta-chave-secreta-jwt-com-pelo-menos-32-caracteres
app.jwt.expiration-ms=86400000

app.commission-api.base-url=http://localhost:8081
app.commission-api.pedido-path=/pedidos
